name: Terraform destroy

on:
  workflow_dispatch

jobs:
  issue_parser:
    runs-on: ubuntu-latest
    name: Terraform destroy
    steps:

    steps:
      - name: Checkout2
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      with:
        working-directory: Terraform-Workspaces
        run: |
          terraform init
          terraform workspace new ${{ env.environment }}
          terraform workspace select ${{ env.environment }} && terraform destroy --auto-approve
