name: Terraform destroy

on:
  workflow_dispatch

jobs:
  issue_parser:
    runs-on: ubuntu-latest
    name: Terraform destroy
    steps:
    - name: Terraform destroy
      env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      uses: aws-actions/terraform-destroy-actions@v3
      with:
        working-directory: aws_s3_bucket
        run: |
          terraform init
          terraform workspace new ${{ env.environment }}
          terraform workspace select ${{ env.environment }} && terraform destroy --auto-approve
